on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions-ecosystem/action-regex-match@v2
        id: tag
        with:
          text: ${{ github.ref }}
          regex: 'v(.+)'

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: togovar/vcf2rdf:latest, togovar/vcf2rdf:${{ steps.tag.outputs.group1 }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
